require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/rants', type: :request do
  # Rant. As you add validations to Rant, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip('Add a hash of attributes valid for your model')
  end

  let(:invalid_attributes) do
    skip('Add a hash of attributes invalid for your model')
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      Rant.create! valid_attributes
      get rants_url
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      rant = Rant.create! valid_attributes
      get rant_url(rant)
      expect(response).to be_successful
    end
  end

  describe 'GET /new' do
    it 'renders a successful response' do
      get new_rant_url
      expect(response).to be_successful
    end
  end

  describe 'GET /edit' do
    it 'render a successful response' do
      rant = Rant.create! valid_attributes
      get edit_rant_url(rant)
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new Rant' do
        expect do
          post rants_url, params: { rant: valid_attributes }
        end.to change(Rant, :count).by(1)
      end

      it 'redirects to the created rant' do
        post rants_url, params: { rant: valid_attributes }
        expect(response).to redirect_to(rant_url(Rant.last))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new Rant' do
        expect do
          post rants_url, params: { rant: invalid_attributes }
        end.to change(Rant, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post rants_url, params: { rant: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) do
        skip('Add a hash of attributes valid for your model')
      end

      it 'updates the requested rant' do
        rant = Rant.create! valid_attributes
        patch rant_url(rant), params: { rant: new_attributes }
        rant.reload
        skip('Add assertions for updated state')
      end

      it 'redirects to the rant' do
        rant = Rant.create! valid_attributes
        patch rant_url(rant), params: { rant: new_attributes }
        rant.reload
        expect(response).to redirect_to(rant_url(rant))
      end
    end

    context 'with invalid parameters' do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        rant = Rant.create! valid_attributes
        patch rant_url(rant), params: { rant: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested rant' do
      rant = Rant.create! valid_attributes
      expect do
        delete rant_url(rant)
      end.to change(Rant, :count).by(-1)
    end

    it 'redirects to the rants list' do
      rant = Rant.create! valid_attributes
      delete rant_url(rant)
      expect(response).to redirect_to(rants_url)
    end
  end
end
